root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run ./cmd/game"
  bin = ""
  include_ext = ["go"]
  exclude_dir = ["assets", "tmp"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 3000

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true